defaults:
  run:
    shell: bash
env:
  GONOPROXY: github.com/getsynq/*
  GONOSUMDB: github.com/getsynq/*
  GOPRIVATE: github.com/getsynq/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-synq-dbt-${{ hashFiles('**/go.sum') }}
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        restore-keys: |
          ${{ runner.os }}-synq-dbt-
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.22"
    - name: Configure git
      run: git config --global --add url."git@github.com:".insteadOf "https://github.com/"
    - name: Build
      run: |
        go get
        go generate
        GOOS=darwin CGO_ENABLED=0 GOARCH=arm64 go build -o synq-dbt-arm64-darwin main.go
        GOOS=linux CGO_ENABLED=0 GOARCH=amd64 go build -o synq-dbt-amd64-linux main.go
        GOOS=linux CGO_ENABLED=0 GOARCH=arm64 go build -o synq-dbt-arm64-linux main.go
        GOOS=windows CGO_ENABLED=0 GOARCH=amd64 go build -o synq-dbt-amd64-windows.exe main.go
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
         synq-dbt-arm64-darwin
         synq-dbt-amd64-linux
         synq-dbt-arm64-linux
         synq-dbt-amd64-windows.exe
name: release synq-dbt
"on":
  push:
    tags:
      - v*.*.*
